Plotting and Animation Improvements
syp2001/KerrGeoPy pull request #1
Opened 2023-10-20 20:48 UTC by syp2001

- Replaced scatter plot with Line3DCollection to prevent the trajectory from breaking up into individual points for very distant orbits
- Fixed a bug that caused the plot to become distorted for low inclination orbits
- Added support for a decaying orbital tail
- Added support for camera movement in animations
- Added tqdm progress bar when rendering animations
- Enabled viewcode sphinx extension

2023-11-05 20:09 UTC, syp2001 commented
Implemented some more ideas that I had. This should hopefully be the last commit on this pull request.

- added background color option
- added support for dynamic zoom
- added option to plot individual components
- fixed typos/errors in documentation

Example:

https://github.com/BlackHolePerturbationToolkit/KerrGeoPy/assets/38138782/1c892919-ca67-48d5-bf7c-96ccc98bbc4b

2023-11-07 14:38 UTC, znasipak requested changes
This looks really good! Package works well when installing the animations branch. I just had one minor comment about capitalizing the word `Mathematica` in the documentation. Otherwise it is ready to merge

2023-11-07 14:38 UTC, znasipak commented on README.md
> +KerrGeoPy is a python implementation of the [KerrGeodesics](https://bhptoolkit.org/KerrGeodesics/) mathematica library. It is intended for use in computing orbital trajectories for extreme-mass-ratio
I would capitalize `Mathematica`

2023-11-07 17:04 UTC, znasipak approved these changes

2023-11-07 17:05 UTC, merged